#!/usr/bin/env bash

##
# Sets up basic server settings on
# newly provisioned hosts
##

: "${username:="jason"}"
: "${password:="f%@nKc5K9kfgMdWHdCLsgvDjTuJXsc3H"}"
: "${default_shell:="bash"}"
: "${dotfiles_directory:="/home/$username/.dotfiles"}"
: "${ssh_public_key:="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPhNCsxxzqX4c0mKcEmuiDdjnaHg2eQtmaTR3RWolf8F Jason@Jasons-MacBook-Pro.local"}"
: "${wifi_ssid:="your_wifi_here"}"
: "${wifi_password:="your_wifi_password_here"}"

###
# Helper functions
##
function info () {
	printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
}
function user () {
	printf "\r  [ \033[0;33m??\033[0m ] %s " "$1"
}
function success () {
	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}
function warn () {
	printf "\r\033[2K  [\033[0;31mWARN\033[0m] %s\n" "$1"
}
function fail () {
	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
	echo ''
	exit 1
}

function check_and_install_package () {
	info "Checking for $1"
	if dpkg -s "$1" > /dev/null 2>&1 ; then
		success "$1 is already installed"
	else
		info "$1 not found, installing now"
		if sudo apt-get install "$1" -y > /dev/null ; then
			success "$1 successfully installed"
		else
			fail "$1 failed to install"
		fi
	fi
}

function change_substring () {
	search=$1
	replace=$2
	file=$3
	sudo sed -i "s/${search}/${replace}/g" "${file}"
}

function check_and_set_auto_settings () {
	change_substring "$1" "$2" /etc/apt/apt.conf.d/50unattended-upgrades
}

function check_and_set_network_settings () {
    change_substring "$1" "$2" /etc/sysctl.conf
}

function check_and_append_settings () {
	if [[ $(grep "$1" "/etc/apt/apt.conf.d/20auto-upgrades") == "" ]]; then
		echo "$1" | sudo tee --append /etc/apt/apt.conf.d/20auto-upgrades &> /dev/null
	fi
}

function setup_wifi() {
    if [[ $(grep "${wifi_ssid}" /etc/wpa_supplicant/wpa_supplicant.conf) == "" ]]; then
        info "Wifi: Adding in wifi"
		{
			echo "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev"
			echo "update_config=1"
			echo "country=US"
			printf "\n\n"
			echo "network={"
			echo "    ssid=\"${wifi_ssid}\""
			echo "    psk=\"${wifi_password}\""
			echo "}"
		} | sudo tee /etc/wpa_supplicant/wpa_supplicant.conf &> /dev/null
		success "Wifi: Successfully setup wifi"
    else
        success "Wifi: Already setup wifi"
    fi
}

function update_and_upgrade () {
	# Updates & upgrades
	info "Updating packages"
	if sudo apt-get update -y > /dev/null ; then
		success "Packages were updated"
	else
		fail "Packages were unable to be updated"
	fi

	info "Upgrading packages"
	if sudo apt-get dist-upgrade -y > /dev/null ; then
		success "Packages were upgraded"
	else
		fail "Packages were unable to be upgraded"
	fi
}

function auto_remove () {
	# Auto removes any unnecessary packages
	info "Auto removing any unnecessary packages"
	if sudo apt-get autoremove -y > /dev/null ; then
		success "All unnecessary packages removed"
	else
		fail "Unable to remove unnecessary packages"
	fi
}

function setup_keyboard() {
    # Sets the keyboard to US if it's not already
    if [[ -f /etc/default/keyboard ]]; then
        if [[ $(grep 'XKBLAYOUT="us"' /etc/default/keyboard) == "" ]]; then
            change_substring 'XKBLAYOUT="\w*"' 'XKBLAYOUT="us"' /etc/default/keyboard
            warn "Keyboard: Successfully set the keyboard default to US, but you'll need to reboot"
        else
            success "Keyboard: Default keyboard is already US"
        fi
    else
        success "Keyboard: No default keyboard config was found"
    fi
}

function setup_user_baseline () {
	# Adds a new user if it doesn't exist
	if [[ $(cut -d: -f1 < /etc/passwd | grep "$username") == "" ]]; then
		# Checks for input password for user, otherwise goes with default
		if [[ $password == "f%@nKc5K9kfgMdWHdCLsgvDjTuJXsc3H" ]]; then
			warn "Warning: Default password was used, please change user password to something else via \`sudo passwd $username\`"
		fi

		sudo useradd -m -p "$password" -s "$(which "$default_shell")" "$username"
		echo "$username:$password" | chpasswd
		success "Created user $username"
	else
		success "User $username already created"
	fi

	# Adds the user to the sudo group if it hasn't been done already
	if [[ $(grep root /etc/group | grep "$username") == "" ]]; then
		sudo gpasswd -a "$username" sudo > /dev/null
		success "User $username has been added to the sudo group"
	else
		success "User $username has already been added to the sudo group"
	fi
}

function setup_user_ssh () {
    # Checks that the baseline directory is good
    if [[ -d /home/${username}/.ssh ]]; then
        success "User SSH: SSH directory already created"
    else
        if sudo -u "${username}" mkdir /home/${username}/.ssh && sudo chmod 700 /home/${username}/.ssh; then
            success "User SSH: SSH directory is now created with the correct permissions"
        else
            fail "User SSH: SSH directory failed to be created with the correct permissions"
        fi
    fi

    # Checks the actual SSH authorized key setup itself
    if [[ -f /home/${username}/.ssh/authorized_keys && $(sudo cat /home/${username}/.ssh/authorized_keys | grep "${ssh_public_key}") == "" ]]; then
        success "User SSH: Authorized key file for user is already created"
    else
        if sudo echo "${ssh_public_key}" >> /home/${username}/.ssh/authorized_keys && sudo chown "${username}:${username}" /home/${username}/.ssh/authorized_keys; then
            success "User SSH: Authorized key file for user is now created"
        else
            fail "User SSH: Authorized key file for user failed to be created"
        fi
    fi
}

function setup_ssh () {
	# Secures SSH daemon
	# Makes a backup
	if [[ ! -d "/etc/ssh/sshd_config.backup" ]]; then
		info "SSHD: Creating a backup of /etc/ssh/sshd_config"
		sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup
	fi

	# Sets it to a non-standard port
	change_substring "Port 22" "Port 30000" /etc/ssh/sshd_config
	success "SSHD: SSH Port is set to 30000"

	# Disallows root access
	change_substring "PermitRootLogin yes" "PermitRootLogin no" /etc/ssh/sshd_config
	success "SSHD: SSH root login is denied"

	# Disallows tunneled plaintext passwords
	change_substring "PasswordAuthentication yes" "PasswordAuthentication no" /etc/ssh/sshd_config
	success "SSHD: SSH tunneled plaintext passwords disabled"

	# Allows ssh access for the user
	if [[ ! $(grep "AllowUsers $username" "/etc/ssh/sshd_config") ]]; then
		if [[ $(grep "AllowUsers" "/etc/ssh/sshd_config") == "" ]]; then
			echo "" | sudo tee --append /etc/ssh/sshd_config > /dev/null # Appends a newline first in case original file isn't newline-terminated
			echo "AllowUsers $username" | sudo tee --append /etc/ssh/sshd_config > /dev/null
		else
			change_substring "AllowUsers" "AllowUsers $username" /etc/ssh/sshd_config
		fi
		success "SSHD: $username has been added to the SSH access list"
	else
		success "SSHD: $username has already been added to the SSH access list"
	fi

	# Restarts ssh daemon
	sudo service ssh restart
}

function setup_auto_update () {
	# Sets up automatic updating
	check_and_install_package unattended-upgrades
	check_and_install_package update-notifier-common

	if [[ ! -f "/etc/apt/apt.conf.d/20auto-upgrades" ]]; then
		# Creates an empty file
		> /etc/apt/apt.conf.d/20auto-upgrades
	fi

	check_and_append_settings "APT::Periodic::Update-Package-Lists \"1\";"
	check_and_append_settings "APT::Periodic::Unattended-Upgrade \"1\";"
	check_and_append_settings "APT::Periodic::AutocleanInterval \"7\";"

	check_and_set_auto_settings "\/\/	\"\${distro_id}:\${distro_codename}-updates\";" "		\"\${distro_id}:\${distro_codename}-updates\";"
	check_and_set_auto_settings "\/\/Unattended-Upgrade::Automatic-Reboot \"false\";" "Unattended-Upgrade::Automatic-Reboot \"true\";"
	check_and_set_auto_settings "\/\/Unattended-Upgrade::Automatic-Reboot-Time \"02:00\";" "Unattended-Upgrade::Automatic-Reboot-Time \"02:00\";"
	success "Auto Updates: All configurations have been set"
}

function setup_ufw () {
	# Sets up ufw (firewall)
	check_and_install_package ufw

	# Alters the SSH default port that the ufw application uses
	change_substring "ports=22" "ports=30000" /etc/ufw/applications.d/openssh-server

	# Checks if it's the first run
	if sudo ufw status &> /dev/null ; then
	    success "UFW: Successfully initialized the firewall"
	else
        warn "UFW: Failed to initialize the firewall (if it's the first time no worries. Rebooting in 5 seconds)"
        sleep 5
        sudo reboot now
	fi

	# Checks to make sure that the ssh port is setup
	if [[ $(sudo ufw show added | grep "ufw limit OpenSSH") == "" ]]; then
		if sudo ufw limit OpenSSH > /dev/null; then
			success "UFW: SSH port has been rate-limited"
		else
			fail "UFW: SSH port could not be rate-limited"
		fi
	fi

	# Checks that it's online and functioning
	if [[ $(sudo ufw status | grep "inactive") != "" ]]; then
		echo "y" | sudo ufw enable > /dev/null

		if [[ $(sudo ufw status | grep "inactive") == "" ]]; then
			success "UFW: Firewall is now active"
		else
			fail "UFW: Unable to activate firewall"
		fi
	else
		success "UFW: Firewall is already enabled"
	fi

	# Checks for sane defaults
	if [[ $(sudo ufw status verbose | grep "deny (incoming)") == "" ]]; then
		if sudo ufw default deny incoming > /dev/null ; then
			success "UFW: Default has been set, all incoming traffic is being denied"
		else
			fail "UFW: Default could not be set, all incoming traffic is allowed"
		fi
	else
		success "UFW: Default is already set to deny all incoming traffic"
	fi

	if [[ $(sudo ufw status verbose | grep "allow (outgoing)") == "" ]]; then
		if sudo ufw default allow outgoing > /dev/null ; then
			success "UFW: Default has been set, all outgoing traffic is allowed"
		else
			fail "UFW: Default could not be set, all outgoing traffic is being denied"
		fi
	else
		success "UFW: Default is already set to allow all outgoing traffic"
	fi
}

function setup_fail2ban () {
	check_and_install_package fail2ban				# Used in ip-banning on both nginx and ufw

	# Creates a local jail to use ufw
	if [ ! -f "/etc/fail2ban/jail.local" ]; then
		info "Fail2Ban: Creating local jail"
		{
			echo "[DEFAULT]"
			echo "ignoreip = 127.0.0.1/8"
			echo "banaction = ufw"
			echo "maxRetry = 5"
			echo "findtime = 600"
			echo "bantime = 7200"
		} | sudo tee /etc/fail2ban/jail.local > /dev/null
		success "Fail2Ban: Local jail created"
	else
		success "Fail2Ban: Local jail already created"
	fi

	sudo service fail2ban restart
}

function setup_shared_memory () {
	info "Shared Memory: Checking security status"
	if [[ $(grep "/run/shm" /etc/fstab) == "" ]]; then
		info "Shared Memory: Memory is currently unsecured, securing now"
		# Note: This only is works in Ubuntu 12.10 or later - For earlier Ubuntu versions replace /run/shm with /dev/shm
		echo "tmpfs     /run/shm     tmpfs     defaults,noexec,nosuid     0     0" | sudo tee --append /etc/fstab > /dev/null
		success "Shared Memory: Memory is now secured"
	else
		success "Shared Memory: Memory is already secured"
	fi
}

function setup_su_privileges () {
	# Checks for admin group existence
	info "Su Privileges: Checking security status"
	if [[ $(grep "admin" /etc/group) == "" ]]; then
		info "Su Privileges: Admin group has not been created, creating now"
		sudo groupadd admin
		success "Su Privileges: Admin group is now created"
	else
		success "Su Privileges: Admin group is already created"
	fi

	# Checks for user inclusion in admin group
	info "Su Privileges: Checking $username's admin status"
	if [[ $(grep "admin" /etc/group | grep $username) == "" ]]; then
		info "Su Privileges: $username is not a part of the admin group, adding $username now"
		sudo usermod -a -G admin $username
		success "Su Privileges: $username has now been added to the admin group"
	else
		success "Su Privileges: $username is already a part of the admin group"
	fi

	# Secures su usage to only admin and root
	info "Su Privileges: Securing su usage to only root and admin"
	if sudo dpkg-statoverride --update --add root admin 4750 /bin/su ; then
		success "Su Privileges: su command is now secured"
	else
		warn "Su Privileges: su command failed to be secure, though it may already be secured"
	fi
}

# Helper function
function setup_network_harden () {
	# Backs up
	if [[ ! -f /etc/sysctl.conf.backup ]]; then
		info "Network: Backing up old sysctl.conf file"
		if sudo cp /etc/sysctl.conf /etc/sysctl.conf.backup ; then
			success "Network: sysctl.conf file is now backed up"
		else
			fail "Network: sysctl.conf file failed to be backed up"
		fi
	fi

	# IP Spoofing protection
	info "Network: Setting IP spoofing protection"
	check_and_set_network_settings "#net.ipv4.conf.default.rp_filter=1" "net.ipv4.conf.default.rp_filter=1"
	check_and_set_network_settings "#net.ipv4.conf.all.rp_filter=1" "net.ipv4.conf.all.rp_filter=1"
	success "Network: IP spoofing protection is enabled"

	# Disable source packet routing
	info "Network: Disabling source packet routing (we are not a router)"
	check_and_set_network_settings "#net.ipv4.conf.all.accept_source_route = 0" "net.ipv4.conf.all.accept_source_route = 0"
	check_and_set_network_settings "#net.ipv6.conf.all.accept_source_route = 0" "net.ipv6.conf.all.accept_source_route = 0"
	success "Network: Source packet routing disabled (we are not a router)"

	# Ignore send redirects
	info "Network: Disabling sending of ICMP redirects (we are not a router)"
	check_and_set_network_settings "#net.ipv4.conf.all.send_redirects = 0" "net.ipv4.conf.all.send_redirects = 0"
	success "Network: ICMP send redirects now ignored by default (we are not a router)"

	# Block SYN attacks
	info "Network: Blocking SYN attacks via SYN cookie enabling"
	check_and_set_network_settings "#net.ipv4.tcp_syncookies=1" "net.ipv4.tcp_syncookies=1"
	success "Network: SYN cookie enabled"

	# Log Martians
	info "Network: Logging Martian packets"
	check_and_set_network_settings "#net.ipv4.conf.all.log_martians = 1" "net.ipv4.conf.all.log_martians = 1"
	success "Network: All Martian packets are now logged"

	# Ignore ICMP redirects
	info "Network: Blocking MitM attacks via ICMP redirect disable"
	check_and_set_network_settings "#net.ipv4.conf.all.accept_redirects = 0" "net.ipv4.conf.all.accept_redirects = 0"
	check_and_set_network_settings "#net.ipv6.conf.all.accept_redirects = 0" "net.ipv6.conf.all.accept_redirects = 0"
	success "Network: ICMP redirects are now disabled"

	# Settings that have to be appended to the file, not changed
	if [[ $(grep "net.ipv4.icmp_echo_ignore_broadcasts" "/etc/sysctl.conf") == "" ]]; then
		{
			echo "# Ignore ICMP broadcast requests"
			echo "net.ipv4.icmp_echo_ignore_broadcasts = 1"
			echo ""
		} | sudo tee --append /etc/sysctl.conf &> /dev/null
		success "Network: ICMP broadcast requests are now ignored"
	else
		success "Network: ICMP broadcast requests are already ignored"
	fi

	if [[ $(grep "net.ipv4.conf.default.accept_source_route" "/etc/sysctl.conf") == "" ]]; then
		{
			echo "# Disable source packet routing"
			echo "net.ipv4.conf.default.accept_source_route = 0"
			echo "net.ipv6.conf.default.accept_source_route = 0"
			echo ""
		} | sudo tee --append /etc/sysctl.conf &> /dev/null
		success "Network: Source packet routing is now disabled"
	else
		success "Network: Source packet routing is already disabled"
	fi

	if [[ $(grep "net.ipv4.conf.default.send_redirects" "/etc/sysctl.conf") == "" ]]; then
		{
			echo "# Ignore send redirects"
			echo "net.ipv4.conf.default.send_redirects = 0"
			echo ""
		} | sudo tee --append /etc/sysctl.conf &> /dev/null
		success "Network: Send redirects are now ignored"
	else
		success "Network: Send redirects are already ignored"
	fi

	if [[ $(grep "net.ipv4.tcp_max_syn_backlog" "/etc/sysctl.conf") == "" ]]; then
		{
			echo "# Block SYN attacks"
			echo "net.ipv4.tcp_max_syn_backlog = 2048"
			echo "net.ipv4.tcp_synack_retries = 2"
			echo "net.ipv4.tcp_syn_retries = 5"
			echo ""
		} | sudo tee --append /etc/sysctl.conf &> /dev/null
		success "Network: SYN flood attacks are now rate-limited"
	else
		success "Network: SYN flood attacks are already rate-limited"
	fi

	if [[ $(grep "net.ipv4.icmp_ignore_bogus_error_responses" "/etc/sysctl.conf") == "" ]]; then
		{
			echo "# Log Martians"
			echo "net.ipv4.icmp_ignore_bogus_error_responses = 1"
			echo ""
		} | sudo tee --append /etc/sysctl.conf &> /dev/null
		success "Network: Martian requests are now logged"
	else
		success "Network: Martian requests are already logged"
	fi

	if [[ $(grep "net.ipv4.conf.default.accept_redirects" "/etc/sysctl.conf") == "" ]]; then
		{
			echo "# Ignore ICMP redirects"
			echo "net.ipv4.conf.default.accept_redirects = 0"
			echo "net.ipv6.conf.default.accept_redirects = 0"
			echo ""
		} | sudo tee --append /etc/sysctl.conf &> /dev/null
		success "Network: ICMP redirects are now ignored"
	else
		success "Network: ICMP redirects are already ignored"
	fi

	if [[ $(grep "net.ipv4.icmp_echo_ignore_all" "/etc/sysctl.conf") == "" ]]; then
		{
			echo "# Ignore Directed pings"
			echo "net.ipv4.icmp_echo_ignore_all = 1"
		} | sudo tee --append /etc/sysctl.conf &> /dev/null
		success "Network: Directeed pings are now ignored"
	else
		success "Network: Directed pings are already ignored"
	fi

	# Reloads sysctl with the latest changes if applicable
	info "Network: Reloading network configurations now"
	sudo sysctl -p &> /dev/null
}

function setup_motd() {
	# Sets up correct motd settings
	if [[ -f /etc/update-motd.d/00-header ]]; then
		sudo mv /etc/update-motd.d/00-header /etc/update-motd.d-00-header.backup
		success "MotD: Disabled header text"
	fi

	if [[ -f /etc/update-motd.d/10-help-text ]]; then
		sudo mv /etc/update-motd.d/10-help-text /etc/update-motd.d-10-help-text.backup
		success "MotD: Disabled help text"
	fi

	if [[ -f /etc/legal ]]; then
		sudo mv /etc/legal /etc/legal.backup
		success "MotD: Disabled legal notice"
	fi
}

function sanity_check() {
    if [[ -f /.server_setup ]]; then
        success "Early Exit: Server is already setup, no need to run setup script"
        exit 0
    else
        info "Setup: Server has not been provisioned before, setting up now"
    fi
}

function mark_success() {
    if [[ -f /.server_setup ]]; then
        success "Mark: Server is already setup"
    else
        if sudo touch /.server_setup ; then
            success "Mark: Successfully marked the server as fully functional"
        else
            fail "Mark: Failed to mark the server as fully functional"
        fi
    fi
}

# Start of actually calling the setup functions
    sanity_check

    # Sets up wifi if it's not setup
    setup_wifi

	# Does server setup
	update_and_upgrade

	# Checks for dependency packages
	check_and_install_package "git"				# Used in dotfile downloading & upkeep
	check_and_install_package "sed"				# Used throughout this program

	auto_remove

    setup_keyboard
	setup_user_baseline
	setup_user_ssh
	setup_ssh
	setup_auto_update
	setup_ufw
	setup_fail2ban
	setup_shared_memory
	setup_su_privileges
	setup_network_harden
	setup_motd

	mark_success

	success "Server setup: Complete"
